### ISSUE TITLE
mount fs with fuse error under Windows

### ISSUE THREAD

**Issue by graphixillusion** [distribyted/distribyted#112]
Hi there. I'm trying to mount with winfsp installed but i always get errors under Windows. Every path i set in the config.yaml i always get this error:

`6:04PM INFCannot create WinFsp-FUSE file system: mount point in use.`

and if i try to specify a drive letter like

`path: "X:"`

i get this error:

`6:07PM INF error mounting filesystems error="mkdir X:.: Unable to find the specified path"`

I'm using last distribyted 0.9.1 version and i've installed the last WinFSP too.

**Comment by ajnavarro** [comment]
Hello @graphixillusion 

I did some tests and standard paths should work. Examples:

- `\test`
- `/test`
- `./distribyted-data/mount` (default path)

Mounting volumes like `X:` is not working right now, I'm preparing a fix.

Could you test with the provided paths and check if it is working for you?

Thanks.

**Comment by graphixillusion** [comment]
Ok, i've understood what's going on: the errors i got with those examples:

- \test
- /test
- ./distribyted-data/mount (default path) 

are becouse the folder must not be present at filesystem level: it will be create by the fuse so when the fuse tries to create the mount point and the folder is already present on the filesystem, it will returns the error (mountpoin alredy in use). This aspect wasn't clear in the documentation so that's why i got problems. So just the fix with the drive letters is needed apparently.

Thank you for the fast answer.

**Comment by ajnavarro** [comment]
No problem!

I will try to improve the error message and the documentation for that case too.

Thanks for reporting the bug! Do not hesitate to open another issue if you encounter other problems.

**Comment by ajnavarro** [comment]
the new https://github.com/distribyted/distribyted/releases/tag/v0.9.2 contains a fix to add support again for drive letters on windows. It will take half an hour to build all the binaries and Docker images.

**Comment by ajnavarro** [comment]
Hi @graphixillusion !

Did the last version fix the issue for you? Thanks!.

**Comment by graphixillusion** [comment]
@ajnavarro yep, it mounts correctly with drive letter, thank you
