### ISSUE TITLE
Multiple file access

### ISSUE THREAD

**Issue by ghostiam** [distribyted/distribyted#12]
Thanks for the project.
If you watch a video and then open a folder or do any action with another file, the video will freeze and the speed graph, after loading the folder, will show 0B/s.
I understand correctly that at the moment it is possible to work with only one file?
What about buffering the video so that chunks are downloaded in advance? I think it's worth putting it into the config.

**Comment by ajnavarro** [comment]
Hey @ghostiam ! thanks for your interest!

>  I understand correctly that at the moment it is possible to work with only one file?

Which OS are you using? I just tested it on Linux and it seems to be able to read two files at the same time:

![screenshot-localhost_4444-2020 10 28-18_57_43](https://user-images.githubusercontent.com/1196465/97477745-4b84bb00-1950-11eb-9888-d5969d53defc.jpg)

Maybe if one of the torrents is not able to provide enough data to the FUSE reader might cause some issues, I need to have a deeper look.

> What about buffering the video so that chunks are downloaded in advance?

All torrent requests are buffering more data chunks than requested from the FUSE filesystem.

**Comment by ghostiam** [comment]
OS: MacOS

**Comment by ghostiam** [comment]
I understood the difference with your screenshot and recorded a video of the problem (it remains to find where I can send it), you have different mountPoints, I have problems within one mountPoints.

**Comment by ghostiam** [comment]
In standard examples, this is not very noticeable, since there are small chunks, in my case the chunks are 4MB in size.

Video: https://nc.ghost.im/s/C4LayNbK9nmMrR4
At the end of the video, you can see more clearly how to unfrezze one editor, and then the file starts to load for the second editor

**Comment by ajnavarro** [comment]
Now I see the problem.

I'm locking every call to fuse implementation, something that I shouldn't do, I need to look into it.

I tried removing the lock when reading and everything appears to work properly. Could you try removing this line?: https://github.com/distribyted/distribyted/blob/master/fuse/mount.go#L61

**Comment by ghostiam** [comment]
I checked it, it doesn't seem to help me.
For tests, I used dd, and as it was before, one file is loaded first, then another. 
```dd if=FILE of=/dev/null bs=1024 count=1000000```

I have a good internet speed, but it seems to me that 1 chunk is being downloaded at a time, because the speed is shifted from one torrent to another and back.

**Comment by ajnavarro** [comment]
I'll have a look into it this weekend.

**Comment by ajnavarro** [comment]
Hi! I just released a new version with a new implementation of the FUSE filesystem. It supports multiple file access. You can have a look here: https://github.com/distribyted/distribyted/releases/tag/v0.4.0-beta2

**Comment by ghostiam** [comment]
Thanks, I'll take a look at the weekend.

**Comment by ajnavarro** [comment]
Fixed on latest release: https://github.com/distribyted/distribyted/releases/tag/v0.4.0
