### ISSUE TITLE
mount fs from user

### ISSUE THREAD

**Issue by GutsyHeart** [distribyted/distribyted#18]
Is it possible to mount files not from the user's root?
Plex does not see files of other users.

**Comment by ajnavarro** [comment]
Hi,

I just had the same problem the other day, trying to create a distribyted Docker image.

I just created a PR with all the new code to allow access to other users to FUSE mounts:

https://github.com/distribyted/distribyted/pull/19

You can try it downloading the generated binaries from here:

https://github.com/distribyted/distribyted/actions/runs/358488127

Note that you need to add `user_allow_other` config flag to `/etc/fuse.conf` file.

**Comment by ajnavarro** [comment]
Fixed on latest release: https://github.com/distribyted/distribyted/releases/tag/v0.4.0
