### ISSUE TITLE
Unable to play media

### ISSUE THREAD

**Issue by Hassall** [distribyted/distribyted#20]
Cloned the repo and did a build make (running linux amd)

Looking at the routes, it does establish a connection fine and I do see a healthy number of seeders and peers for the torrents. 

I tried adding a new magnet uri and that works fine. The folder gets created but trying to play the media (via vlc) doesn't work, i just get a vlc error saying unable to open the file. 

I tried using one of the default media in the configs and that doesn't work either. The only one that had some progress was the .webm file (tears of steel) that opens a webpage and loads. I see data being downloaded but it isn't streaming to the player.

I don't see any obvious errors/logs relating to my issue

**Comment by ajnavarro** [comment]
Hi,

I cannot help too much with this, one of my use cases is use VLC with distribyted, and AFAIK it is working OK.

Do you have a good enough internet connection? 
Might your ISP limit torrent traffic? 
Are other torrent clients working properly?

**Comment by HaleemDream** [comment]
My internet works fine. Using streaming service from BitTorrent web while downloading works well.

I did try to use the prebuilt binary as well before and same results.

**Comment by ajnavarro** [comment]
Are you able to retrieve file content with other programs than VLC? per example, doing a `cat` of the file.

**Comment by ajnavarro** [comment]
Unable to reproduce.
