### ISSUE TITLE
Every file and folder an automatic torrent

### ISSUE THREAD

**Issue by balupton** [distribyted/distribyted#30]
Found this project looking for torrent fuse mount projects, this one seems the most supported and active.

I am wondering about the feasibility of this, a fuse mount, where each file and folder gets their own torrent, such that I can have a free structured mount file system, and be able to get a torrent for any file or folder within it, and share it to others knowing the fuse mount is auto seeding/leeching it.

I can also open a torrent or magnet file in a helper, that will ask me where in the fuse mount I wish to save it to, which upon completion, generates torrents for each file and folder within that save.

This would enable a good cross-platform and cross-language ecosystem to be built atop of it, as applications would just need to add files/folders to the fuse mount then query the meta data for the torrent details.

downloading a torrent would still need an api it would seem

**Comment by ajnavarro** [comment]
I like your idea!

I was thinking to try to be as standard as possible. As a first step, I can implement a new folder where you can throw at it torrent files, which will be automatically mounted and show to the user as a standard folder.

In the near future, we can do the opposite too! you can add to this folder a new archive or folder that you want to share, and distribyted will create a new torrent for you on that folder. You can share that torrent with anyone that wants to access your files.

This can open a lot of new possibilities.

**Comment by balupton** [comment]
Just recognised I may have a gap in my understanding about the practicality of such an approach.

if say file A and file B are both in directory C, and we want to generate torrents for all, we will get three torrents.

now if someone is torrenting directory C, will the seeds of the torrent of file A and the torrent of file B also be able to seed to those downloading those files from directory C? Or will they go ignored and only seeds of the torrent of directory C be able to seed those files?

**Comment by ajnavarro** [comment]
I see,

I was thinking of generating torrents only for root folders or files, or mounting torrents from root only too. Per instance:
- Special distribyted folder ROOT, we add a new torrent, automatically we can see the torrent content as a new folder with the same name as the torrent file.
- If we want to share some file or folder, we copy it to the ROOT directory. Automatically we will see a new torrent file with the same name as the file/folder that we can share with anyone.

Adding that logic into subdirectories might cause a lot of corner cases as you mentioned.

**Comment by ajnavarro** [comment]
Implemented here https://github.com/distribyted/distribyted/pull/90 (magnet link creation from a folder)
