### ISSUE TITLE
Option to disable IPV6

### ISSUE THREAD

**Issue by fabianski7** [distribyted/distribyted#48]
My network does not have IPV6 support, and when I start distribyted in this environment, the console displays a huge amount of errors.

Example:

```
go-libutp: 2021/04/01 12:07:49 callbacks.go:73: error sending packet: write udp6 [::]:42069->[2804:14d:78c4:42be:5c6f:1f28:595d:6a11]:47107: sendto: cannot assign requested address
go-libutp: 2021/04/01 12:07:52 callbacks.go:73: error sending packet: write udp6 [::]:42069->[2804:14d:78c4:42be:5c6f:1f28:595d:6a11]:47107: sendto: cannot assign requested address
go-libutp: 2021/04/01 12:07:56 callbacks.go:73: error sending packet: write udp6 [::]:42069->[2804:14d:78c4:42be:5c6f:1f28:595d:6a11]:47107: sendto: cannot assign requested address
```

I would like to take this opportunity and thank you for this amazing tool. I have been looking for something like this for a long time and finally found it. THANKS!

**Comment by ajnavarro** [comment]
Hi @fabianski7 ! thanks for reporting this.

I just created a new PR changing configuration format to make new features easier to implement. I added the possibility of disabling IPV6: https://github.com/distribyted/distribyted/pull/49

It will be available in the next release.

Also thank you for using distribyted! Do not hesitate to give any feedback or new ideas!

**Comment by fabianski7** [comment]
Thanks for the answer @ajnavarro 
I am looking forward to testing the new version
thanks

**Comment by ajnavarro** [comment]
Added in 0.7.0
