### ISSUE TITLE
High CPU usage when disconnected from the internet

### ISSUE THREAD

**Issue by fabianski7** [distribyted/distribyted#55]
When the process is running, and the internet connection is lost, the distribyted process starts using almost the entire CPU (after a few minutes).

There is no different log in the terminal, only what I have already reported [here](https://github.com/distribyted/distribyted/issues/48)

![ksnip_tmp_ceXvGT](https://user-images.githubusercontent.com/47755037/114923857-daad5e80-9e1c-11eb-9758-57e4eb878763.png)

Operating System: Arch Linux
KDE Plasma Version: 5.21.4
Kernel Version: 5.11.13-arch1-1

**Comment by ajnavarro** [comment]
Thanks @fabianski7 for the heads up, I'll have a look ASAP.

**Comment by ajnavarro** [comment]
Problem fixed in latest version
