### ISSUE TITLE
Torrents are not being added

### ISSUE THREAD

**Issue by fabianski7** [distribyted/distribyted#88]
I just updated distribyted to version 0.7.0.1 and none of my old config files are working anymore. The webserver is started but no torrents are mounted.

[Here is an example](https://bin.disroot.org/?e762b1e5472b5a11#BjUZnnoyWnR5TznKne7Yinqg2Rg3tcHrqyZMqV8FkhYQ)
```

$  distribyted --config ~/.tmp/distribyted/core/config/fun.yml 
5:52PM INF All 0 tables opened in 0s component=item-store
5:52PM INF Discard stats nextEmptySlot: 0 component=item-store
5:52PM INF Set nextTxnTs to 0 component=item-store
5:52PM INF Deleting empty file: distribyted-data/metadata/items/000021.vlog component=item-store
5:52PM INF All 0 tables opened in 0s component=torrent-store
5:52PM INF Discard stats nextEmptySlot: 0 component=torrent-store
5:52PM INF Set nextTxnTs to 0 component=torrent-store
5:52PM INF Deleting empty file: distribyted-data/metadata/magnetdb/000021.vlog component=torrent-store
5:52PM INF setting cache size to 1024 MB
5:52PM INF adding torrents from configuration component=torrent-service
5:52PM INF adding torrents from database component=torrent-service
5:52PM INF starting FUSE mount path=./distribyted-data/mount
5:52PM WRN webDAV configuration not found!
5:52PM INF starting webserver host=0.0.0.0:4444
```

**Comment by ajnavarro** [comment]
Hi,

I had to change the configuration structure to make possible new features. Have a look here:

https://github.com/distribyted/distribyted/blob/master/templates/config_template.yaml

Cheers.

**Comment by fabianski7** [comment]
Yes, I realised. so I copied the template file, and just added the magnetic links and made some other small changes.
[Here a visual diff](https://user-images.githubusercontent.com/47755037/142474693-770c93d3-21ae-47ca-a87a-15cc0eff740d.png)

**Comment by ajnavarro** [comment]
Did it finally work?

**Comment by fabianski7** [comment]
> Did it finally work?

No. The diff I sent was already from the file I tried to use on the first attempt, and it didn't work

**Comment by fabianski7** [comment]
uhh, i just noticed that we now have `magnet_uri` instead of `magnetUri`. sorry

**Comment by ajnavarro** [comment]
No problem! Do not hesitate to open issues if you have other problems.
